pipeline {
    agent {
        label 'build.dev.cloud.im'
    }
    environment {
        SEMANTIC_VERSION=sh(returnStdout: true, script: "git describe --exact-match ${GIT_COMMIT} --abbrev=0 --tags || echo 'v0.0.0-dev'").trim()

        PROJECT_NAME="rndi-connect-devops-fulfillment-framework"
        PROJECT_KEY="connectors-${PROJECT_NAME}"
        PROJECT_VERSION="${SEMANTIC_VERSION}" + "${SEMANTIC_VERSION == 'v0.0.0-dev' ? '.' : '-'}" + "${BUILD_NUMBER}"
    }
    stages {
        stage('Environment Setup') {
            steps {
                sh """
                /usr/local/bin/python3.8 -m venv venv
                source venv/bin/activate

                pip install --upgrade pip
                pip install pylint poetry --trusted-host pypi.int.zone
                """
            }
        }
        stage('Install Dependencies') {
            steps {
                sh """
                source venv/bin/activate

                poetry check
                poetry install
                """
            }
        }
        stage('Check Code Style') {
            steps {
                sh """
                source venv/bin/activate
                poetry run flake8
                """
            }
        }
        stage('Test Execution') {
            steps {
                sh """
                source venv/bin/activate
                poetry run pytest
                """
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    def SCANNER_HOME = tool name: 'SonarQubeIntZoneScanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation';
                    withSonarQubeEnv('SonarQubeIntZone') {
                        sh """
                        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.project.tags=connectors \
                        -Dsonar.projectVersion=${PROJECT_VERSION} \
                        -Dsonar.projectKey=${PROJECT_KEY} \
                        -Dsonar.sources=rndi/ \
                        -Dsonar.tests=tests/ \
                        -Dsonar.python.coverage.reportPaths=coverage.xml \
                        -Dsonar.python.pylint=venv/bin/pylint
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}